### ISSUE TITLE
[Bug]: Chart panel sometimes does not open directly

### ISSUE THREAD

**Issue by ericboucher** [WFP-VAM/prism-app#1012]
### What happened?

From time to time, the chart panel does not open as expected on first click. This happens sporadically but seems to happen more if the window is shrunk (eg. console panel opened at the bottom)

### Which country / deployment are you running?

All / master

**Comment by ericboucher** [comment]
This happens to me pretty consistently with the console opened at the bottom but not in normal use. Other devs are not able to reproduce so closing for now. I did investigate a bit but could not find anything obvious. Removing a few memos around tabs and panels did not seem to help.

https://github.com/WFP-VAM/prism-app/assets/16843267/edda83ae-c44a-4970-b8f5-9a21e951d02a

**Comment by v1n35h** [comment]
Hey @neo773, I see you're active in many open issues. I'd like to tackle this one, mind if I take a shot at it? Thanks!

**Comment by oliverqx** [comment]
@ericboucher will the bounty be awarded?

**Comment by neo773** [comment]
cc
@zcesur
