### ISSUE TITLE
[Bug]: Commit hash text can overlap with layer navigation

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#1017]
### What happened?

If the list of layers is expanded, the commit hash text introduced in PR https://github.com/WFP-VAM/prism-app/pull/1001 can overlap with the layer navigation.

Can we remove the commit hash text from the UI and put it in the console instead? Any other suggestions @ericboucher?

### Which country / deployment are you running?

Zimbabwe / main

### Add a screenshot (if relevant)

See bottom left:
<img width="1676" alt="Screenshot 2023-12-11 at 13 49 27" src="https://github.com/WFP-VAM/prism-app/assets/3343536/0f1c0803-cc1b-45af-af3a-2e096b5c2c44">

**Comment by ericboucher** [comment]
@wadhwamatic we can put it in the console, and/or just add it at the bottom of the layer menu at the end of it, in that case it would only appear if you scroll down
