### ISSUE TITLE
[Feature Request]: Allow a user to pan, zoom and crop before 'printing' a map

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#1019]
### Provide a clear and concise description of what you want to happen.

Users want to be able to have more control when they export a map from PRISM using the 'print' feature. 

After clicking on the 'print' button, a user gets to the map preview screen. In this screen, I want to able to:
1. Pan the map
2. Zoom in/out
3. Crop the map

It's important to be able to do this in the map preview screen because the main application has other UI elements in view which obscure the map which is then exported.

Panning and zooming should behave the same as in the application (i.e. click / drag to pan, and use mouse / trackpad to zoom).

Cropping will need a new button which should be added to the right side panel:
![print-update](https://github.com/WFP-VAM/prism-app/assets/3343536/02d1d18b-daf0-4510-bc53-b766cf0b7632)

After clicking the crop button, users should be able to drag from the edges of the canvas to crop to the area of interest similar to how photo editing software works:
https://github.com/WFP-VAM/prism-app/assets/3343536/4d4b0ceb-82cc-4e8b-bef6-5097ecbd8fb6

**Comment by echaidemenos** [comment]
hello @wadhwamatic. About the cropping functionality, would you like to change the exported image's width or height? The behavior in video linked above, i believe can be achieved by zooming and panning

**Comment by wadhwamatic** [comment]
Hi @echaidemenos - if possible, it would be good to give the ability to adjust the canvas size too. That way users can adjust the size according to what works best for their area of interest. "Wide" countries like Indonesia would likely be cropped differently than "narrow" countries like Mozambique.
