### ISSUE TITLE
[Bug]: Country name in charts header for RBD is incorrect

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#1026]
### What happened?

The label used in charts at country level show the admin code instead of the admin name

Steps to reproduce:
1. country=RBD
2. Go to charts and toggle 'compare locations' on
3. Select any two countries
4. Select any chart
5. See that the header of the chart shows two letters instead of the full name. This is the admin code, not the admin name

### Which country / deployment are you running?

RBD on main

### Add a screenshot (if relevant)

<img width="1499" alt="Screenshot 2023-12-12 at 19 43 56" src="https://github.com/WFP-VAM/prism-app/assets/3343536/7644c801-1896-4a4c-88ac-ef4f1effdc97">

**Comment by ericboucher** [comment]
Linked to #992
