### ISSUE TITLE
[Bug]: layers with days validity cause an error when running an analysis

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#1027]
### What happened?

If I try to run analysis on a data layer which has days validity configured, the calendar picker lets a user select a date which may not exist on the server which then causes an error.

Steps to reproduce:
1. country=RBD
2. Go to the Analysis tab
3. Choose 10-day rainfall aggregate for the hazard layer and admin boundaries for the baseline layer
4. Choose 2-Dec-2023 as the date and then click run analysis
5. An error is returned
6. Change the date to 1-Dec-2023 and try again. No error

### Which country / deployment are you running?

RBD on main

### Add a screenshot (if relevant)
<img width="1301" alt="Screenshot 2023-12-12 at 20 07 09" src="https://github.com/WFP-VAM/prism-app/assets/3343536/389baecd-ad9c-42bf-ab5e-767db6ffffac">

**Comment by wadhwamatic** [comment]
@ericboucher - should we revisit the purpose of days of validity? It's needed for intersecting layers, and for visualizing date ranges. Wondering if we made this overly complicated with the current approach.

**Comment by ericboucher** [comment]
Good catch, I see two options here:
1. Keep all the dates in the validity and then get the correct query date
2. Only show available query dates in the calendar
