### ISSUE TITLE
[Feature Request]: Revisit print UI, including additional elements - title and text size

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#1076]
### Provide a clear and concise description of what you want to happen.

Users have requested that we provide the option to include a title when we print a map, and to make the footer text size adjustable.

Let's revisit the print feature UI while we are at it.  I think we should allow all text elements to have adjustable sizes. They could just be small, medium, large to not make things too complicated. It would also be good if we can edit text in the same screen instead of loading a modal.

Below is just a suggestion and includes a change mentioned in issue 1051. @ericboucher, can we have Marc also take a look?
![crop-map](https://github.com/WFP-VAM/prism-app/assets/3343536/00e44919-c9d2-4c87-a6fc-f14ff5ab3d83)

### Is there anything else you can add about the proposal? You might want to link to related issues here, if you haven't already.

See issue https://github.com/WFP-VAM/prism-app/issues/1051

_No response_

**Comment by ericboucher** [comment]
Let's use the option 1 in - https://www.figma.com/file/5GX8jVxBCfLrcfkTniRvFi/WFP-Prism?type=design&node-id=361-6&mode=design&t=z99kKdMwwDB9rlbr-0
For the boundary selector, let's leverage the goto dropdown selector used for alerts and the mask implemented in #1086

**Comment by ericboucher** [comment]
Linked to https://github.com/WFP-VAM/prism-app/issues/1076

**Comment by ericboucher** [comment]
Let's also update the downloaded file name to `prism_map_COUNTRY_DATE`
