### ISSUE TITLE
[Feature Request]: Get Anticipatory Action trigger and threshold data from a CSV file

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#1099]
### Provide a clear and concise description of what you want to happen.

This is a placeholder for now with more details to come. For the upcoming AA module, the current workflow includes production of trigger status, and forecasted indicators over time. These outputs are then stored in a series of CSV files. PRISM will need to access this data, based on location and time period. 

@paololucchino - can you please link to an example CSV?

See issue https://github.com/WFP-VAM/prism-app/issues/1098 for a broader overview of the AA module and some mockups

**Comment by ericboucher** [comment]
[SPI_probabilities_season_triggers.csv](https://github.com/WFP-VAM/prism-app/files/14571734/SPI_probabilities_season_triggers.csv)
