### ISSUE TITLE
Dedicated property for text legend class

### ISSUE THREAD

**Issue by mwarizmiwafiq** [WFP-VAM/prism-app#111]
The current implementation of text legend class is to read the value properties. While now it can accommodate number and text, the way it implements somehow a bit confusing (I assume it will process integer/number first, then put all "value" including string for render the legend element.

What I would like to purpose is a dedicated "text" property for legend. Which can provide a more flexible and predictable way to generate text for legend, while separating the class for value classification.

"legend": [
      {
        "value": -40,
        "color": "#7ab1c0",
        "text": "-40° C"
      },

First I would like to have input from @ericboucher about the idea. I would like to put the changes as part of understanding the ideal workflow of adding features into prism workflow.

**Comment by wadhwamatic** [comment]
Let's get this in the work plan. Rather than using the term 'text', I'd suggest 'label'

**Comment by wadhwamatic** [comment]
This was addressed via https://github.com/WFP-VAM/prism-app/pull/327
