### ISSUE TITLE
Charts load time

### ISSUE THREAD

**Issue by ericboucher** [WFP-VAM/prism-app#1111]
It seems that charts are loading much faster on Firefox than Chrome, even when working with new requests.

Let's investigate where the difference could stem from between the two and improve performance on Chrome if possible.

**Comment by mehulmathur16** [comment]
@ericboucher can I be assigned?

**Comment by mehulmathur16** [comment]
Hi @ericboucher, I got caught up in some other works. I'll setup the codebase and check this out today.

**Comment by mehulmathur16** [comment]
@ericboucher I wasn't able to find anything specific for load time differences. Also on my machine, the performance was near about same on both the browsers. Hence, unassigning myself from the issue.

**Comment by ericboucher** [comment]
@feliciien any luck? I might close this issue otherwise since we don't seem to be able to replicate well.

**Comment by Bhavyajain21** [comment]
@ericboucher I'd like to give it a try

**Comment by MAYANK-TRIPATH** [comment]
Hi @ericboucher I tried it on both chrome and firefox and dont find any delay or slowness in chrome. Both are working fine and at same speed. also tracked in performance tab. didnt find any major differences.

**Comment by raphaelbernhart** [comment]
@ericboucher Is this still open/needed?
