### ISSUE TITLE
Time-series choropleth map (area) from API

### ISSUE THREAD

**Issue by mwarizmiwafiq** [WFP-VAM/prism-app#112]
PRISM should have support to display a choropleth map (from statistics data in JSON format) with time-series variable. For example is to show the poverty rate in district level from year to year, or to support rendering "old version" of impact layers (the data also in statistics and JSON format).

PRISM already have the "NSO" layer type which can display choropleth map and also "point_data" which render selected time-series data from given link. I think the approach that we can use is NSO layer with capabilities to get and render data from API just like "point_data".

IDCO would like to prioritize in this feature as we need it to display socio-economic layer (ideally in time series so people can compare the changes from year to year) and support for "legacy" impact layer data. But first I would like to clarify and ask some question to @ericboucher and @dubwalla:

- I would like to just confirm if the feature mentioned above is not already supported, or RBB team is currently developing a similar feature?

- Should we create new category, or should we just expand from NSO layer type with more parameters something like: "timeseries": true, "data": http://linktoapi, etc.

- Should we have more standardize API? Or should we make it more flexible, so user can setup the "GET" format in config file alongside with layer properties. 

Thank you.

**Comment by dubwalla** [comment]
Thanks Wafiq. This is a common need across deployments and something we mentioned to Ovio before. I think adding a time attribute to existing structures is the way to go.  I'm adding this to the overall tracking sheet too. We may need to rewrite this as a more generalizable issue

**Comment by wadhwamatic** [comment]
Addressed through https://github.com/WFP-VAM/prism-app/pull/555
