### ISSUE TITLE
Send notification if Date Loading Fails

### ISSUE THREAD

**Issue by Ry-DS** [WFP-VAM/prism-app#114]
Currently, if dates fail to load from WMS, WCS or Point Data, an error is sent to the console. There used to be a notification, served through the error notification middleware, but this was removed because if an exception is thrown in serverUtils, all the other layers would not attempt loading dates. 

To solve this, a notification could be dispatched instead of relying on the error middleware.
Not too much of a concern as date errors aren't likely to happen, but would be nice to solve eventually

https://github.com/WFP-VAM/prism-frontend/blob/5c68143ff2e15ac95127c8f5ceac673293d7096d/src/utils/server-utils.ts#L180

**Comment by wadhwamatic** [comment]
Relates to https://github.com/WFP-VAM/prism-app/issues/593
