### ISSUE TITLE
[Bug]: Multiple labels in the map preview screen aren't translating 

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#1176]
### What happened?

The options for the print feature (title, mask, select admin, etc.) are not translated. I added text in this PR https://github.com/WFP-VAM/prism-app/pull/1175

### Which country / deployment are you running?

https://github.com/WFP-VAM/prism-app/pull/1175 / Kyrgyzstan

### Add a screenshot (if relevant)

<img width="1444" alt="Screenshot 2024-03-25 at 18 15 28" src="https://github.com/WFP-VAM/prism-app/assets/3343536/3dd29632-71e0-4f10-90ac-87c3ba16c18a">

**Comment by ericboucher** [comment]
Fixed in #1174
