### ISSUE TITLE
[Bug]: Extracted GeoTIFF is cutoff 

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#1187]
### What happened?

When I downloaded a raster for Mozambique (hazardLayerIds=precip_blended_dekad&date=2024-03-21), the resulting file's southern data is cutoff

### Which country / deployment are you running?

Mozambique / Main

### Add a screenshot (if relevant)

<img width="1743" alt="Screenshot 2024-04-09 at 06 39 41" src="https://github.com/WFP-VAM/prism-app/assets/3343536/d752b0c3-c03c-4215-8fed-fc63bcfaa937">

GeoTIFF extent in QGIS:
<img width="628" alt="Screenshot 2024-04-09 at 06 37 20" src="https://github.com/WFP-VAM/prism-app/assets/3343536/0aeff8ff-0ac6-4ffb-8069-8bf0d50d0f5c">

This is the downloaded file:
[mozambique_precip_blended_dekad_2024-03-21.tif.zip](https://github.com/WFP-VAM/prism-app/files/14919235/mozambique_precip_blended_dekad_2024-03-21.tif.zip)

**Comment by ericboucher** [comment]
@wadhwamatic you need to update the map bounding box to go a bit more south. I seem to remember that we had fixed this in some unmerged PR already
