### ISSUE TITLE
[Feature Request]: Add more details in the tooltip for analysis results layer

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#1190]
### Provide a clear and concise description of what you want to happen.

It's easy to lose analysis results context when you click on a tooltip and see statistics for an admin area. For example, I can run an analysis for rainfall in March, while also visualizing a rainfall layer in October. 

In this screenshot, I've run analysis for 3-month SPI in March, but am visualizing the 3-month SPI layer in October. The tooltip shows the analysis result (March), which doesn't match the layer in view (October).

<img width="1750" alt="Screenshot 2024-04-10 at 20 56 21" src="https://github.com/WFP-VAM/prism-app/assets/3343536/3922f951-b1a1-40ce-a958-f18b7e58c1b4">

We should add details to the tooltip to make it clear what the statistic refers to. In this case, it should say:
Sofala, Muanza
SPI - 3-month (Mean) 21-March-2024: -1.58.

**Comment by ericboucher** [comment]
We were discussing this with Mark the other day.

We could also imagine creating a date for the analysis and only showing layers that are valid on that date. Or default to using the current selectedDate to run the analysis

**Comment by wadhwamatic** [comment]
We should definitely default to using current selectedDate when a user moves to the analysis tab.
And adding a date attribute to the results makes sense too.

I would still propose adding more info to the tooltip on dates. I think we should also consider adding dates to the legend (with full validity). This is what I wanted to discuss more broadly for improving date visualization.
