### ISSUE TITLE
[Feature Request]: Allow users to change the position of the legend from left to right side when printing

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#1197]
### Provide a clear and concise description of what you want to happen.

When in print mode, users have requested the ability to move the legend to the right side of the screen. This would also match the view in PRISM.

Modify the print preview screen to include legend position with the options: left, right, none. We can then remove the visibility option from the legend size selection.

**Comment by ericboucher** [comment]
I suggest using these icons:
eye-closed, NorthWest, NorthEast

https://mui.com/material-ui/material-icons/?query=left&selected=NorthWest
