### ISSUE TITLE
[Feature Request]: Make print feature's footer text configurable text

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#1208]
### Provide a clear and concise description of what you want to happen.

Users have requested to modify the default footer text in the print screen, or to remove it altogether. I propose that we add an attribute in prism.json to handle this. 

As an example, within prism.json, I want to be able to do the following:
1. Make the footer visible or hidden
2. Set the default footer text

"print_footer": [
  {
    "show": true,
    "default_text": "Enter default footer text here"
  }

Open to other suggestions!

**Comment by wadhwamatic** [comment]
@ericboucher - sorry some issues here:

1. I don't see the default text anymore even if I remove the defaultFooterText parameter from prism.json
2. I also don't know how we can continue to show the date of the layers displayed with this change

See this new issue: https://github.com/WFP-VAM/prism-app/issues/1222

**Comment by ericboucher** [comment]
@echaidemenos let's address 1. now in the shared prism.json and address 2 as part of #1222
