### ISSUE TITLE
[Bug]: AA module legend is not consistent with other layers

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#1215]
### What happened?

The legend for the AA module is not consistent with other layers. The font size is larger and the window is wider. Can we reformat the AA legend to match others? 

### Which country / deployment are you running?

Mozambique, main

### Add a screenshot (if relevant)

<img width="1798" alt="Screenshot 2024-04-30 at 12 47 00" src="https://github.com/WFP-VAM/prism-app/assets/3343536/c5ef2c65-27dc-4374-9b0e-d6b11616bd95">

**Comment by ericboucher** [comment]
@echaidemenos https://www.figma.com/file/Xe8H1GuVMJUsIi4JNTYPVo/WFP-Anticipatory-Action-(AA)?type=design&node-id=1346-661&mode=design&t=3nZqVoypEvdaEHT2-4
