### ISSUE TITLE
[Bug]: AA module - missing "mild" info from "how to read this screen" popup

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#1217]
### What happened?

Missing mild drought information in popup window

### Which country / deployment are you running?

Mozambique, main

### Add a screenshot (if relevant)

<img width="611" alt="Screenshot 2024-04-30 at 13 07 04" src="https://github.com/WFP-VAM/prism-app/assets/3343536/4a9007f5-78a8-4abc-962e-eab5764095b1">

**Comment by echaidemenos** [comment]
Do we know what the description of Mild should be here?
