### ISSUE TITLE
[Bug]: AA module - timeline view's content doesn't change when user selects another date

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#1219]
### What happened?

The AA timeline view doesn't refresh if you select a district and then move the date using the bottom timeline picker. I am not particularly clear on what should happen but do see that the forecast view does changes if you choose a different date.

Side note - I've always used the term timeline to describe the bottom data picker in PRISM. We now introduced another UI element called timeline. This will be confusing. Can we find another name for the AA timeline?

### Which country / deployment are you running?

Mozambique, main

### Add a screenshot (if relevant)

Timeline view Dec 2023:
<img width="1798" alt="Screenshot 2024-04-30 at 15 55 47" src="https://github.com/WFP-VAM/prism-app/assets/3343536/4557b014-1575-44f7-a0d7-f966e8f2c291">

Timeline view Sept 2023:
<img width="1797" alt="Screenshot 2024-04-30 at 15 55 56" src="https://github.com/WFP-VAM/prism-app/assets/3343536/55f32fc8-18b3-4d31-aedf-0b9831ad72c8">

Forecast view Dec 2023:
<img width="1799" alt="Screenshot 2024-04-30 at 15 56 34" src="https://github.com/WFP-VAM/prism-app/assets/3343536/922141a8-c233-40d9-aaac-26efe180ad7d">

Forecast view Sept 2023:
<img width="1803" alt="Screenshot 2024-04-30 at 15 56 26" src="https://github.com/WFP-VAM/prism-app/assets/3343536/56d1fac7-9fc4-4ab8-97da-6a5778e08b7b">

**Comment by ericboucher** [comment]
@wadhwamatic that the expected behavior:
- the timeline displays all available info month by month for that district, so the selected date does not have any effect on it
- the forecast shows the latest probabilities available at the selected date
