### ISSUE TITLE
[Feature Request]: AA module - add trigger values in the forecast view

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#1220]
### Provide a clear and concise description of what you want to happen.

Gabriela requested that we add the indicator and threshold values in the forecast view. I asked Marc to create a design for this. 

The mockup below isn't a design, just to show what I mean by forecast screen and trigger / threshold values. Let's get designs from Marc before implementing.

![forecast+values](https://github.com/WFP-VAM/prism-app/assets/3343536/a0b6b448-3ee3-4672-bd5a-d5274329037e)

**Comment by Marco6x1** [comment]
here is the mockup, Gabriela preferred to suggest a trigger has been exceeded with an icon rather than displaying the values. https://www.figma.com/file/Xe8H1GuVMJUsIi4JNTYPVo/WFP-Anticipatory-Action-(AA)?type=design&node-id=1329-586&mode=design&t=3nZqVoypEvdaEHT2-4
