### ISSUE TITLE
[Feature Request]: AA module - UI to get back to the district window / action view is unclear

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#1221]
### Provide a clear and concise description of what you want to happen.

If I select a district on the map, I get a view which shows phases and actions in a timeline view. If I then click either the forecast or timeline buttons, the only way to return to the previous view is to click the left arrow at the top of the module next to the district name. This is not intuitive. 

I suggest adding a back button next to the area timeline and forecast buttons

![back](https://github.com/WFP-VAM/prism-app/assets/3343536/7b6f5ede-6622-47c8-948c-4e4bd8a15eaa)

**Comment by Marco6x1** [comment]
Here are the updated mockups: 
https://www.figma.com/file/Xe8H1GuVMJUsIi4JNTYPVo/WFP-Anticipatory-Action-(AA)?type=design&node-id=510-8000&mode=design&t=3nZqVoypEvdaEHT2-4
https://www.figma.com/file/Xe8H1GuVMJUsIi4JNTYPVo/WFP-Anticipatory-Action-(AA)?type=design&node-id=1329-586&mode=design&t=3nZqVoypEvdaEHT2-4

We should add one as well on this one no? https://www.figma.com/file/Xe8H1GuVMJUsIi4JNTYPVo/WFP-Anticipatory-Action-(AA)?type=design&node-id=506-6134&mode=design&t=3nZqVoypEvdaEHT2-4

**Comment by wadhwamatic** [comment]
@ericboucher - yeah, that's fair. Maybe it should say 'District overview'? I'll ask Gabriela what she thinks too

**Comment by Marco6x1** [comment]
In my understanding it was a real back => you go back to forecast in your example.
But if you prefer otherwise I’ll respect that :)
