### ISSUE TITLE
[Feature Request]: Make date ranges more clear

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#1224]
### Provide a clear and concise description of what you want to happen.

The current approach for displaying dates in PRISM isn't fully addressing how dates are work in HDC. In HDC, dates refer to the last dekad (10-day period) of any data product. In PRISM, we can visualize start and end dates a few ways, but haven't successfully visualized the ranges of a specific product in a clear way

Here's what I think we need to do:
1. Get the start and end date for a single observation for timeline visualization purposes. 
2. Don't visualize date ranges for an observation until it's selected. For example, if a data layer is valid for 1-month, don't show solid bars for every month, just show ticks for the dekads available, and a full month bar when a specific observation is selected
3. Add information about the selected observation's dates to the bottom of the legend

This quick mockup attempts to illustrate these ideas. I know Marc is working on some designs too.
 
![timeline-rev](https://github.com/WFP-VAM/prism-app/assets/3343536/bdf64f6e-e298-418c-9fa2-ba8b00c47c45)

Light grey: available dates
Black: selected observation start date
Light blue: date range for selected layer / observation
![timeline](https://github.com/WFP-VAM/prism-app/assets/3343536/e65e9684-cb7a-4783-987f-b6249b58b51c)

**Comment by ericboucher** [comment]
https://www.figma.com/design/5GX8jVxBCfLrcfkTniRvFi/WFP-Prism?node-id=696-1918&t=BLdhJUkThOB3FuD2-0
