### ISSUE TITLE
[Bug]: Analysis results are not covering all of Mozambique, and the view table feature no longer works

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#1229]
### What happened?

Not sure when this was introduced, but I found two issues when running an analysis:
1. Results are not available for the full country. Guessing this is a bounding box issue again. We should probably add a buffer to the boundaries to avoid this
2. 'View table' feature no longer works, you just see a white screen

### Which country / deployment are you running?

Mozambique, main

### Add a screenshot (if relevant)

See missing data in the northeast and far south. Table results are also not showing.

<img width="1653" alt="Screenshot 2024-05-01 at 16 48 33" src="https://github.com/WFP-VAM/prism-app/assets/3343536/b3a60deb-f66a-49b4-aa0e-4405ed226b2f">

**Comment by ericboucher** [comment]
@echaidemenos can you look into 2. ?
