### ISSUE TITLE
Download data layer

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#124]
Allow a user to download data as a CSV for tabular / vector data and as a GeoTIFF for raster data. The same UI element should allow a user to download the selected data layer regardless of the type of data. 

Suggestion: The UI should include a download link / button within the context of the current legend area. At a later date, we may revisit this and create a more extensive UI for interacting with layers.

**Comment by erwagasore** [comment]
I have realized that there are many places where the user can download either data or images. We can try to consolidate those user's actions to one central location. I had a discussion with @dubwalla suggesting having a layers sidebar. Below is a mockup of how that would look like.

![Prism - Layers hidden](https://user-images.githubusercontent.com/1290048/117296404-4d868400-ae75-11eb-9e1f-bdcc8ee0ecd9.png)

![Prism - Layers Mockup](https://user-images.githubusercontent.com/1290048/117296456-5e36fa00-ae75-11eb-8016-1305c98a0fd9.png)

I took inspiration from some implementations of ![TerriaJS](https://nsw.digitaltwin.terria.io/)
Please tell me how you see it ;)

**Comment by erwagasore** [comment]
This suggestion also took into consideration of some already created branches `idn_dev` and another one for `layer opacity`

**Comment by wadhwamatic** [comment]
@ericboucher - temporarily assigning this to you (Ovio) but feel free to close this and refer to a new issue or the related ones ([618](https://github.com/WFP-VAM/prism-app/issues/618), [209](https://github.com/WFP-VAM/prism-app/issues/209))
