### ISSUE TITLE
[Feature Request]: Use a config option to display labels instead of values in the tooltip

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#1280]
### Provide a clear and concise description of what you want to happen.

In many cases, `admin_level_data` layers represent categorical variables. For example, in RBD, the `ifpri_conflict_2023` layer uses the data field `ACI_value` which range from 1-4. The numeric values have a concept of ranking, but not of a real value. 

When a user clicks on the map, the tooltip shows the numeric value (i.e. '1', '2', '3', '4'). I want to be able to optionally configure `admin_level_data` to use `label` instead of `value` in the tooltip. We can do this using `feature_info_props` by adding an attribute such as `source`. See the example below

```
    "feature_info_props": {
      "ACI_value": {
        "type": "string",
        "source": "label",
        "dataTitle": "Classification"
      }, 
```

This would then make use of the label associated with each value configured in the legend of this layer:
```
    "legend": [
      {
        "label": "Low / Inactive",
        "value": 1,
        "color": "#e6e6e6"
      },
      {
        "label": "Turbulent",
        "value": 2,
        "color": "#1f77b3"
      },
      {
        "label": "High",
        "value": 3,
        "color": "#f4a582"
      },
      {
        "label": "Extreme",
        "value": 4,
        "color": "#e51a19"
      }
    ]
```

The change mentioned above should show this:

> Mali, Gao, Menaka
> IFPRI / ACLED Conflict Analysis - 2023
> Classification: Extreme

A side note - the term `feature_info_props` is pretty abstract. If we can look into changing this to `tooltip` or something more clear, that would be appreciated too!

**Comment by wadhwamatic** [comment]
The RBD configuration mentioned above is in https://github.com/WFP-VAM/prism-app/pull/1189

**Comment by gislawill** [comment]
Example for Will to reference later
<img width="1479" alt="Screenshot 2024-06-18 at 11 44 08 AM" src="https://github.com/WFP-VAM/prism-app/assets/8203830/e7208d3d-7f2d-47c2-8e47-ebdee5a00969">
