### ISSUE TITLE
[Feature Request]: Allow for fill patterns in admin level data layers for individual values

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#1282]
### Provide a clear and concise description of what you want to happen.

We have a request to visualize a layer which has a combination of solid and striped fill patterns. As of now, I can create a layer which has solid fill patterns or left / right striped fill patterns, but not a combination of both.

I want to be able to configure fill patterns at the individual value level like this:
```
"legend": [
      {
        "label": "Priority 1a",
        "value": 1,
        "color": "#b30101",
        "fill_pattern": "left"
      },
      {
        "label": "Priority 1",
        "value": 2,
        "color": "#b30101"
      },
      {
        "label": "Priority 2",
        "value": 3,
        "color": "#e24a32"
      },
      {
        "label": "Priority 3",
        "value": 4,
        "color": "#fcca8b"
      },
      {
        "label": "Priority 4",
        "value": 5,
        "color": "#fff0d9"
      }
```

This will allow me to create a layer that matches what is seen in this map:
![RBDRAM_FSHotspotAnalysis_Jun24_Draft01](https://github.com/WFP-VAM/prism-app/assets/3343536/ba5a0fee-e0a5-45fb-bfb7-a4762ee711bc)

### Is there anything else you can add about the proposal? You might want to link to related issues here, if you haven't already.

Fill patterns for admin level data layers were added in this PR: https://github.com/WFP-VAM/prism-app/pull/869

**Comment by ericboucher** [comment]
Fixed in #1283
