### ISSUE TITLE
[Bug]: Fill patterns show a repeating white triangle

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#1285]
### What happened?

When I load a layer with a `fill_pattern`, the layer renders with repeated white triangles that become more prevalent as you zoom in.

Steps to reproduce:
1. Use rbd-add-fsn-hotspot-layers branch
2. REACT_APP_COUNTRY=rbd yarn start
3. Load layer: Food security and nutrition hotspots > Food security and nutrition analysis > Food security hotspots
4. See the series of white triangles that appear within the striped pattern for Priority 1a values
5. Zoom in further to see more prevalent triangles

### Which country / deployment are you running?

RBD; https://github.com/WFP-VAM/prism-app/pull/1283

### Add a screenshot (if relevant)

<img width="1745" alt="Screenshot 2024-06-25 at 18 27 30" src="https://github.com/WFP-VAM/prism-app/assets/3343536/31c348d4-7098-4d22-9049-d25c3dbece73">

When further zoomed in:
<img width="1750" alt="Screenshot 2024-06-25 at 18 27 38" src="https://github.com/WFP-VAM/prism-app/assets/3343536/cfe2ea1e-14e6-46c7-89c1-34e450b8449a">

**Comment by ericboucher** [comment]
Fixed in #1283

**Comment by ericboucher** [comment]
<img width="430" alt="Screenshot 2024-06-26 at 12 46 15 PM" src="https://github.com/WFP-VAM/prism-app/assets/16843267/bff024d4-2d89-4ff4-9793-e7d568d130f0">
