### ISSUE TITLE
[Bug]: Empty analysis results for a few locations in West Africa

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#1293]
### What happened?

Analysis results are missing in some areas in West Africa as seen in the map, and in the table results.

Missing areas:
- Côte d'Ivoire, Agneby-Tiassa, Taabo
- Côte d'Ivoire, Agneby-Tiassa, Tiassalé
- Côte d'Ivoire, Agneby-Tiassa, Sikensi
- Côte d'Ivoire, Agneby-Tiassa, Agboville
- Mali, Gao, Menaka
- Cabo Verde, Ribeira Brava, Nossa Senhora Da Lapa

Steps to reproduce this issue:
1. REACT_APP_COUNTRY=rbd yarn start
2. Run analysis > Choose any hazard layer > Choose Admin 2 > leave other options as default
3. See polygons with no values in Mali, Cabo Verde and Cote d'Ivoire
4. Click on table view. The default sort is by name and you'll see locations without names at the beginning of the list

### Which country / deployment are you running?

Main / RBD

### Add a screenshot (if relevant)

Missing analysis results data in Mali:
<img width="1646" alt="Screenshot 2024-06-27 at 11 32 17" src="https://github.com/WFP-VAM/prism-app/assets/3343536/91c03f34-65b4-491a-832a-75be68f24ee2">

Rows of analysis results without a name:
<img width="924" alt="Screenshot 2024-06-27 at 11 44 12" src="https://github.com/WFP-VAM/prism-app/assets/3343536/e63c87b8-1492-4504-81d5-867498f29862">

**Comment by ericboucher** [comment]
@wadhwamatic I believe this was already fixed by #1289, no?

**Comment by ericboucher** [comment]
![Screenshot 2024-07-02 at 4 54 59 PM](https://github.com/WFP-VAM/prism-app/assets/16843267/8de1641b-b288-4e01-a42b-396856fc1d5e)

**Comment by wadhwamatic** [comment]
@ericboucher - yup, fixed via https://github.com/WFP-VAM/prism-app/pull/1289
