### ISSUE TITLE
[Bug]: CSV download of analysis results is incomplete

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#1294]
### What happened?

After I ran an analysis, I downloaded the results as a CSV but several rows of data that are shown in PRISM are not included in the CSV file. I think this is related to the name of the location. The CSV is missing data after the location 'Liberia, Grand Bassa, District # 1'

Steps to reproduce:
1. REACT_APP_COUNTRY=rbd yarn start
2. Run analysis > Choose any hazard layer > Choose Admin 2 > leave other options as default
4. Click on table view. Note in the footer of the table view, there should be 2044 rows of data
5. Download the results as a CSV. See that there are only 893 rows of data with the last entry missing a value and the name is not fully captured (it should say 'District #1')

### Which country / deployment are you running?

RBD / main

### Add a screenshot (if relevant)

Analysis results have 2044 rows, and  District # 1 has data: 
<img width="1660" alt="Screenshot 2024-07-01 at 15 29 43" src="https://github.com/WFP-VAM/prism-app/assets/3343536/ced9e735-78cb-4741-9a8a-546355145cff">

CSV has 894 rows, and the last entry doesn't have the full name ('District # 1') or value
<img width="447" alt="Screenshot 2024-07-01 at 15 39 20" src="https://github.com/WFP-VAM/prism-app/assets/3343536/d6e1bc0b-0c79-4370-b11c-4b23181aac14">

**Comment by ericboucher** [comment]
Fixed in https://github.com/WFP-VAM/prism-app/pull/1291/commits/43d1f8e8d0d7b388fb0d3803cd1434f8aeb557db
