### ISSUE TITLE
[Bug]: Analysis results failing for layers with scale factors [correction: layers without EPSG 4326 projection)

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#1298]
### What happened?

This issue surfaced when testing PR https://github.com/WFP-VAM/prism-app/pull/1297 though is not related to the PR.

If I run analysis for a layer with a scale factor set using `wcsConfig` in layers.json, I get three types of errors: either all values are zero, null, or are equal to the offset value. I tested this in Mozambique and RBD and see the same issue in both cases

These are the errors per layer (see screenshots in the next section)
- NDVI. All values rounded to zero
- NDVI anomaly returns all null values
- LST amplitude. All values rounded to zero
- LST daytime, LST nighttime, INAM air temperature. All values equal to offset (-273)
- LST anomaly returns all null values

Steps to reproduce:
1.  REACT_APP_COUNTRY=mozambique yarn start
2. Run analysis with any of the above hazard layers, lowest level admin boundary as baseline (admin 3 for Mozambique), default for all others
3. View table to see values for each admin area

### Which country / deployment are you running?

main / mozambique & RBD

### Add a screenshot (if relevant)

NDVI (all zeroes):
<img width="1883" alt="Screenshot 2024-07-04 at 14 48 51" src="https://github.com/WFP-VAM/prism-app/assets/3343536/9efb75d6-ab49-4aca-a015-c731e7f2016a">

LST (all values = offset)
<img width="1883" alt="Screenshot 2024-07-04 at 15 00 57" src="https://github.com/WFP-VAM/prism-app/assets/3343536/7e8a9956-5127-47b2-a222-f9c7a5963614">

LST anomaly (null values):
<img width="1888" alt="Screenshot 2024-07-04 at 14 53 52" src="https://github.com/WFP-VAM/prism-app/assets/3343536/e3fff0a1-68a4-4179-a406-a6cf427042e1">

LST amplitude (all zeroes):
<img width="1882" alt="Screenshot 2024-07-04 at 14 53 00" src="https://github.com/WFP-VAM/prism-app/assets/3343536/c15177ee-4c1a-47ae-8d2c-b601a727f8c5">

**Comment by ericboucher** [comment]
@wadhwamatic I investigated the issue and indeed it looks like the problem is in the backend. More specifically, this has been introduced by the switch to STAC.

However I am not exactly sure what is happening. It could be a resolution issue or something to do with no_data representations.

Here are a few files for testing for devs which can be used with the following parameters:

{"geotiff_url":"{working or not working file}","zones_url":"https://prism-admin-boundaries.s3.us-east-2.amazonaws.com/moz_bnd_adm2_WFP.json","group_by":"adm2_source_id","geojson_out":false}'

[Archive.zip](https://github.com/user-attachments/files/16110370/Archive.zip)

**Comment by wadhwamatic** [comment]
Thanks @ericboucher. Looping in @valpesendorfer to help us troubleshoot this issue.

Valentin - production of zonal stats is failing on a few layers. Eric has found a couple of issues that arose after the switch to STAC. The layers causing issues are:
- NDVI. All values rounded to zero
- NDVI anomaly returns all null values
- LST amplitude. All values rounded to zero
- LST daytime, LST nighttime, INAM air temperature. All values equal to offset (-273)
- LST anomaly returns all null values

Could you take a look and let's try to sync early next week?

**Comment by ericboucher** [comment]
@wadhwamatic @valpesendorfer nota bene - on our end it does not seem to be an issue with the "scale factor" per say since the scaling is happening in the frontend. But maybe there is something different happening in the processing of these layers on the STAC side?

**Comment by valpesendorfer** [comment]
Sorry I didn't have time yet to dive into this. But just to clarify - there's no processing happening on STAC side. The STAC item is just a metadata construct with the link to the actual file on S3 (scaled if applicable) and the corresponding metadata (collection, extent, nodata & scale factor if applicable).

So by switching to STAC either you were relying on something which happened automatically through WCS, or the change in the logic introduced a bug.

**Comment by wadhwamatic** [comment]
@ericboucher - looking again, for the example of NDVI anomaly, it looks like the error happens before the PRISM stats API request. The `raster_geotiff` query fails with a 500 error. 

Related to this query, when I saw Valentin recently, he mentioned briefly that this part of the PRISM data request process doesn't make sense. We're writing a second version of a GeoTIFF to S3 on the PRISM side that already exists on HDC S3 storage. I don't remember why we introduced this when we switched to STAC requests. This query is also exposing a key. Let's revisit the logic of the `raster_geotiff` request.

**Comment by valpesendorfer** [comment]
Ok, so I had a look and I know what's the issue:

The STAC API just serves the metadata information for HDC's STAC collections and their items, and that's it. All processing tasks are a responsibility of the client. When you switched over to STAC from OWS, you assumed all of these responsibilities which were partially taken over at that point by the OWS server.

In particular, this is about the reprojection - all the datasets above are not in `epsg:4326`, but rather in the native MODIS projection. Previously, you requested the TIFF from WCS and the server did the reprojection for you. Now switching to STAC, the client needs to take care of reprojection. 

If you look at the two example rasters above (working & not working) you see they both have data - just one is in `epsg:4326` and one not. What I'm assuming is happening in the analysis step is that you're trying to extract values with an `epsg:4326` vector layer, which does not find any values at these locations, returning zeros/null/whatever.

Two proposals for a solution:

- fix the desired projection to `epsg:4326` and make sure the raster is reprojected on the backend on read
- re-project the vector file on the backend before you do the extraction and analysis

TBH, the second option is the cleaner, more flexible and by different measures "more correct" one.

**Comment by wadhwamatic** [comment]
Thanks @valpesendorfer for digging into this and clarifying what has caused the issue. I see that all of the problematic layers are indeed MODIS derived (LST & NDVI). 

I agree that the second option seems more correct as we should build awareness and handling of projections during the analysis process. I see that the HDC STAC catalog includes projection data at the item level. 

@ericboucher - here's an example of two different projections coming from HDC data (not sure if those links will work for you though)

CHIRPS 10-day rainfall (https://data.earthobservation.vam.wfp.org/stac#/collections/rfh_dekad/items/rfh_dekad-202406d3)
<img width="848" alt="Screenshot 2024-07-08 at 19 17 15" src="https://github.com/WFP-VAM/prism-app/assets/3343536/f2e26707-fbf9-4755-b997-f85146481c06">

MODIS 10-day NDVI anomaly (https://data.earthobservation.vam.wfp.org/stac#/collections/mxd13a2_viq_dekad/items/mxd13a2_viq_dekad-h27v09-202406d3)
<img width="851" alt="Screenshot 2024-07-08 at 19 16 05" src="https://github.com/WFP-VAM/prism-app/assets/3343536/0d9c636f-7c2f-4842-b52e-4853eb01412d">

I'd like to hear Eric's thoughts on implementing this on the PRISM API side and then would consider this a good issue for @lowriech or @gislawill to work on.
