### ISSUE TITLE
[Bug]: admin 1 and admin 2 level analysis fails for Mozambique

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#1299]
### What happened?

When I tried to run an analysis at admin level 1 or 2, I get an error response 'failed to fetch'. Level 3 works as expected.

I'm not sure what would cause this and if it was undetected when we merged PR https://github.com/WFP-VAM/prism-app/pull/1163 or if a change that came later caused the issue. I thought perhaps this is related to the boundary file but I'm not seeing any issues in the file.

Steps to reproduce:
1.  REACT_APP_COUNTRY=mozambique yarn start
2. Run analysis using any hazard layer, baseline layer = admin 2, default all other inputs
3. See the error in PRISM
4. Try again with  baseline layer = admin 3. Results will appear as expected

### Which country / deployment are you running?

main / mozambique

### Add a screenshot (if relevant)

<img width="1883" alt="Screenshot 2024-07-04 at 15 49 33" src="https://github.com/WFP-VAM/prism-app/assets/3343536/efc3bf88-a6de-4221-9f44-65e00c4e5e78">

**Comment by ericboucher** [comment]
@wadhwamatic it fails locally because the key we use does not exist on the file uploaded in S3 but it should work on deployed versions. But i think in general we should find a better way to do this and stop relying on the uploaded files altogether

**Comment by wadhwamatic** [comment]
Thanks for looking into this @ericboucher. I updated the files on S3 so that they are the same as what we have locally but it still failed. I'll do a quick deploy to double-check though.

Agreed, good if we can move away from relying on remote files in this case.

**Comment by ericboucher** [comment]
@wadhwamatic I think we fixed that with the `?v2` trick in the file name, correct?
