### ISSUE TITLE
[Bug]: Timestamp for Cambodia EWS-1294 data is incorrect

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#1314]
### What happened?

I'm not sure when this bug was introduced, it may have been quite a while ago. When I view the EWS-1294 chart data, the timestamps should reflect local time in Cambodia. When I view the chart now at 12:30 PM in San Francisco, I should be seeing  timestamps reflecting the current time in Cambodia (2:30 am) but instead am seeing 9:30 am.

Steps to reproduce:
1.  REACT_APP_COUNTRY=cambodia yarn start
2. Activate layer: Flood > Early Warning > EWS-1294
3. Click on a point and see the chart data
4. Note the [current local time in Cambodia](https://www.timeanddate.com/worldclock/cambodia/phnom-penh)
5. The last data point in the chart's timestamp should be close to local time in Cambodia

### Which country / deployment are you running?

Cambodia / main

### Add a screenshot (if relevant)

Current behavior on main at 12:30 pm SF / 2:30 am Cambodia:
<img width="1206" alt="Screenshot 2024-07-17 at 12 39 46" src="https://github.com/user-attachments/assets/cf9cb7d8-d5f3-402e-ad2d-550f9e5675b5">

Behavior on an older version of 
<img width="1112" alt="Screenshot 2024-07-17 at 12 43 57" src="https://github.com/user-attachments/assets/92131fe9-a80a-44e1-b5eb-da537a68ac95">
PRISM at the same time:

**Comment by ericboucher** [comment]
Tentatively fixed in https://github.com/WFP-VAM/prism-app/pull/1301/commits/831254fd53bee2d89930368319302bdf209688d3

**Comment by ericboucher** [comment]
@wadhwamatic @gislawill please check that it is fixed for you in SF and then we can close this if it is.

**Comment by gislawill** [comment]
Looks good to me, here's what I see
<img width="1006" alt="Screenshot 2024-08-01 at 6 10 18 PM" src="https://github.com/user-attachments/assets/f07d2dc5-b78d-4131-9db6-92cf79ffedb3">
<img width="762" alt="Screenshot 2024-08-01 at 6 10 23 PM" src="https://github.com/user-attachments/assets/8db6427c-00f4-4fc9-a7ff-af780077b40d">
