### ISSUE TITLE
[Feature Request]: Allow users to download CDI / q-multi results

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#1336]
### Provide a clear and concise description of what you want to happen.

Users have requested the ability to download CDI results through PRISM. The download button should be implemented the same as other layers - within the navigation panel and the legend. 

### Is there anything else you can add about the proposal? You might want to link to related issues here, if you haven't already.

From my understanding, the result from the q-multi function is a geojson object with point-level data. Can we simply expose this data for download without too much additional effort?

**Comment by gislawill** [comment]
That's right, the hip-service endpoints provides PRISM with a geojson that we can allow users to download pretty easily. We would need a different approach after https://github.com/WFP-VAM/prism-app/issues/1337 to provide with admin boundaries (depending on our implementation).

Do you have a preference on the order of operations @wadhwamatic? I have a slight preference for getting this one in first while we discuss the approach for #1337

**Comment by wadhwamatic** [comment]
Yes, I agree @gislawill - let's work on downloading the point data first and we can revisit for admin bound CDI once 1337 is done. Thanks!
