### ISSUE TITLE
Support for animations

### ISSUE THREAD

**Issue by valpesendorfer** [WFP-VAM/prism-app#237]
There's [ongoing work at datacube-ows](https://github.com/opendatacube/datacube-ows/pull/659) to support animations in [APNG](https://en.wikipedia.org/wiki/APNG) format served out of WMS.

Question:

- Would that be interesting for PRISM?
- Could that be supported?

**Comment by valpesendorfer** [comment]
`datacube-ows` [version 1.8.15](https://github.com/opendatacube/datacube-ows/releases/tag/1.8.15) now has experimental support for animations. 

I've played around a little bit with it, and this is a first result:

![rfh_anim](https://user-images.githubusercontent.com/18698817/128638057-87908677-bec1-40cb-ba2b-83f3d0f4c04f.png)

generated by the following request:

http://odc.ovio.org/wms?version=1.3.0&request=GetMap&format=image%2Fpng&transparent=true&exceptions=application%2Fvnd.ogc.se_inimage&crs=EPSG:4326&width=256&height=256&time=2021-05-11&layers=rfh_dekad&bbox=0,0,10,10&styles=rfh_anim&time=2021-06-21,2021-07-01,2021-07-11

Curious to hear thoughts on feasibility and interest for PRISM and start a discussion @wadhwamatic @ericboucher

**Comment by wadhwamatic** [comment]
@valpesendorfer - cleaning up old issues and came across this one. I don't see animation styles available from HDC's API. This isn't a priority on our side at the moment, but before I close this, wanted to check and see if you were planning to deploy animation styles again

**Comment by valpesendorfer** [comment]
@wadhwamatic indeed I’ve removed it from the current deployment, as there wasn’t any interest from anyone. I have it parked somewhere, so we can revisit it but I’m honestly not sure if it ever got properly implemented on datacube-ows side

**Comment by wadhwamatic** [comment]
Thanks @valpesendorfer. I'll close this for now. I can see some value for this, but nothing concrete at the moment
