### ISSUE TITLE
mVAM / hungermap monitoring data integration

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#311]
For three of our upcoming deployments (Namibia, Zimbabwe, and Mozambique), we need to support admin_level_data which is retrieved from the Hunger Monitoring unit's API. The API includes a few metrics which can vary from country to country. On the PRISM side, we would want to fetch metrics of interest for a given country and make them accessible as individual layers. 

There are a few challenges:
1. The API uses admin boundaries and codes from a common tool called the GeoEnabler managed by WFP's Emergencies Division
2. The API currently only exposes the last 100 days of data. 
3. Notably, every day in the last 100 days has valid day. But there is not a dates available request from the API as of yet

Starting with Namibia has an example, we want to bring in the 'fcs' and 'rcsi' measures from the API. This is an example of the API request / endpoint: https://api.hungermapdata.org/v1/foodsecurity/country/NAM/region?date_start=2021-10-01

See the related issue https://github.com/WFP-VAM/prism-frontend/issues/277 which will get a unique boundary file per admin level layer. This integration will also require a unique boundary file which comes from the GeoEnabler.

**Comment by wadhwamatic** [comment]
Adding more details here following a call with HMU team today. 
1. We'll need to get the boundary file and host it directly. Disregard earlier notes about GeoEnabler. Awaiting boundary data / polygons instead
2. End date can be added to the API request. For example, this request will get 5 days of data. https://api.hungermapdata.org/v1/foodsecurity/country/NAM/region?date_start=2021-10-01&date_end=2021-10-05
3. We're still limited to the 100 most recent days of data. There's no endpoint to query available dates. But we can assume there's daily data starting 100 days ago and until today. 
4. There are multiple indicators in the endpoint. We would create a separate admin_level_data layer for each indicator by only need to get the response from the API once

Anything I missed @erwagasore and @JorgeMartinezG ?

**Comment by wadhwamatic** [comment]
@erwagasore - I've added IDs which match those used by the HungerMap API to a boundary json and placed it here (WFP internal at the moment): https://wfp.sharepoint.com/:u:/s/PRISM/ESApcqY4oq9NmKMMEvgLKEUBfBY0m7vIUsp-FuX2qMJxcg?e=cAyXgr 

The field 'mvam-Code' matches with the region id used in the API as seen here: https://api.hungermapdata.org/v1/foodsecurity/country/MOZ/region?date_start=2021-12-01&date_end=2021-12-08 

Given that I was able to match the region ID in this case to our existing boundary file, we should just be able use the revised boundary file (admin level 1) and focus on parsing the API endpoint for the creation of a new layer in PRISM.

**Comment by wadhwamatic** [comment]
@erwagasore - I looked again at the boundary file that I sent, and it has no issues that I can see. But I realized that I think you were trying to work with Myanmar still?? This is for Mozambique, that would be one very obvious reason why the layer didn't show up when you were testing. =)

**Comment by erwagasore** [comment]
Will look into it and found out the real issue, but was working with Mozambique not Myanmar.

**Comment by wadhwamatic** [comment]
Closing as this is not a priority for the foreseeable future
