### ISSUE TITLE
Integrate Cambodia's IDPoor data into PRISM

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#349]
The IDPoor system in Cambodia reports the number of households registered as poor by administrative area. For the upcoming deployment of PRISM in Cambodia, we need to ingrate this data as an admin_level_data layer type. The IDPoor data does not seem to be updated frequently and we're not sure about the reliability / performance of the API. 

Details about the IDPoor system can be found here: https://mop.idpoor.gov.kh/about/documents
Some light documentation on the API is here: https://mop.idpoor.gov.kh/api/external/swagger-ui.html
A query builder (which uses the API) is here: https://mop.idpoor.gov.kh/reporting/builder

A few challenges / caveats:
1. The IDPoor data collection occurs over multiple rounds over time. But from a data visualization / analysis perspective, we should retrieve the latest IDPoor data nationally, which is assembled over multiple rounds over time
2. The gazeteer codes used by the IDPoor system do not align with admin codes we've used. A boundary file that matches the IDPoor codes is available from the WFP Cambodia office
3. Multiple queries are also required to obtain all admin areas, as the queries for lower admin areas are unique to their parent. For example, to get admin2 data, a query is required for each admin1 area. In this example query, '3' is an admin1 code: https://mop.idpoor.gov.kh/api/analytics/public/units/3/children?region=ALL&isOnDemand=ALL&year=2019&round=ALL

**Comment by wadhwamatic** [comment]
See also: https://docs.google.com/document/d/11nuAKVPKUTXnmLieLpgSKhJyZK2Xzdqos8iBKwk7K90/edit#heading=h.lmenolaz2xfh

**Comment by ericboucher** [comment]
@wadhwamatic how often is the data updated?

**Comment by wadhwamatic** [comment]
> @wadhwamatic how often is the data updated?

@ericboucher - I was trying to find the answer to this yesterday as well. I think at most, twice a year. Will confirm. Definitely ok to store locally and check for updates rather than fetching data every time

**Comment by ericboucher** [comment]
If that's the case, then I think we should either store it locally and have a prebuild script that checks for updates. Or simply load at build time using `https://nextjs.org/docs/basic-features/data-fetching/get-static-props`. Do we know how reliable their API is?

**Comment by wadhwamatic** [comment]
> If that's the case, then I think we should either store it locally and have a prebuild script that checks for updates. Or simply load at build time using `https://nextjs.org/docs/basic-features/data-fetching/get-static-props`. Do we know how reliable their API is?

that sounds good to me. I don't know how reliable the API is, so all the more reason to take the approach you're suggesting

**Comment by wadhwamatic** [comment]
Closing this for now as we don't have updates on the IDPoor API
