### ISSUE TITLE
Surface temperature returned from Data Cube needs to be converted to celsius

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#43]
The Data Cube returns Land Surface Temperature (LST) in a scaled-Kelvin format. We need to display data in Celsius. Two steps are needed:
1. Scale to degrees Kelvin by multiplying by 0.02
2. Convert to Celsius by subtracting 273

Reference:
https://icess.eri.ucsb.edu/modis/LstUsrGuide/usrguide_mod11.html#sds

**Comment by bencpeters** [comment]
This is really easy to add with the new code in #55. We just need to add another type of layer for WCS data processed on the front end (vs. WMS tiles)

**Comment by SimplyBallistic** [comment]
From my understanding, we are looking to display the correct surface temperature in Celsius once you click on a boundary, right? 

If this is correct, completing #64 should be done first to ensure the infrastructure is in place to display boundary data onClick in a `WMSLayer`

**Comment by bencpeters** [comment]
> If this is correct, should #64 be completed first to ensure the infrastructure is in place to display boundary data onClick in a `WMSLayer`?

I _think_ this is more or less the same issue as #64 - the data that @dubwalla is talking about here is the data that we want to display for the tooltip.

**Comment by dubwalla** [comment]
Yes, this builds off of the issue of #64, but there's the additional component of unit conversion. Fetch, convert, display

**Comment by wadhwamatic** [comment]
Addressed via https://github.com/WFP-VAM/prism-app/pull/220
