### ISSUE TITLE
Input required on how to require authentication for non-WFP users for specific data layers

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#477]
In the context of Cambodia, data collected through mobile forms (Kobo toolbox) should not be accessible to the general public. There's a need to explore potential solutions which can 1) securely authenticate PRISM Cambodia users within government, 2) be compatible with WFP's own requirements on user authentication, 3) not require a WFP login.

**Comment by ericboucher** [comment]
@wadhwamatic closing for now, if `4` is true we might need to revisit the logic a bit. For now it seemed that all the forms we were looking at had a `Province` field.
