### ISSUE TITLE
Admin level data layers with date dimension

### ISSUE THREAD

**Issue by reed1** [WFP-VAM/prism-app#504]
Normally, admin level data will have one static json file, we need a feature to allow admin level data having different json files for different time / date. We have several vector layers with date dimension in Indonesia, for example "Drought affected population" :

https://prism.wfp.or.id/app/?baselineLayerId=dslr_pop&date=2021-08-18

![image](https://user-images.githubusercontent.com/1814324/177080932-efd5b22f-c31d-4494-abc0-7c79feca5a9d.png)

Previously it was implemented on IDN branch. I made a branch for the feature here: [feature/admin-level-with-dates](https://github.com/WFP-VAM/prism-frontend/tree/feature/admin-level-with-dates). Please review @wadhwamatic , if it's good I can make a PR for the branch

**Comment by wadhwamatic** [comment]
@reed1 - Please go ahead and create a PR and include instructions on how to test. I don't see clearly how we will implement this in the layer configuration like we discussed. I.e., where is the date attribute served from if we're serving from local files?

**Comment by wadhwamatic** [comment]
@reed1 - can we please move this forward? Thanks!

**Comment by reed1** [comment]
@wadhwamatic I add config example here : https://github.com/WFP-VAM/prism-frontend/commit/8a1ef42949ec89eaa231539e83c5339e14359906

Will revert once done. Basically putting path and date_url in config like this:

```  
"total_pop_dated": {
    "title": "Total population with date",
    "type": "admin_level_data",
    "date_url": "data/myanmar/pop/dates.json",
    "path": "data/myanmar/pop/pop_{YYYY-MM-DD}.json",
...
```

We're using it with additional web backend service, but if you put it as relative path to data folder it should be fine too

**Comment by wadhwamatic** [comment]
@reed1 - can you please create a PR for this? It's been waiting for your action for a very long time now.

**Comment by wadhwamatic** [comment]
I went ahead and created PR https://github.com/WFP-VAM/prism-frontend/pull/555 for this branch and issue. @reed1 - we need to address how this date feature works with dates more broadly. I'll add another deployment to this branch / PR
