### ISSUE TITLE
Look into solutions to improve performance of Kobo API 

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#564]
The Kobo API utilized for PRISM Cambodia is extremely slow and at times fails to respond altogether. We've talked about caching as one option to try first. I think we might want to consider deploying our own Kobo instance as well.

**Comment by wadhwamatic** [comment]
Re: local Kobo install: https://github.com/kobotoolbox/kobo-install

**Comment by ericboucher** [comment]
Potentially linked to #487

**Comment by ericboucher** [comment]
Some other solutions include caching the `dates` query

**Comment by wadhwamatic** [comment]
This has been addressed through https://github.com/WFP-VAM/prism-app/pull/592. We can create a new issue if performance issues persist, but it's significantly improved now.
