### ISSUE TITLE
Feature request: add optional fill pattern for admin level data layers

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#578]
For the PRISM deployment to WFP's Regional Bureau in Dakar (RBD), we have a complicated set of admin level data layers that should be visible at the same time as a group. The group includes two datasets that are at the admin 2 level. Both layers visualize the same type of data, but one of them is collected under unique circumstances (the area that it describes is partly inaccessible, or the population that the data describes is unique, such as internally displaced people - IDPs). 

To visualize these two layers together, a fill-pattern could be used to differentiate them. The screenshot below shows an attempt to differentiate the two layers using opacity.
<img width="1438" alt="Screen Shot 2022-10-04 at 21 29 28" src="https://user-images.githubusercontent.com/3343536/193981653-21f33918-73f5-4926-9fa2-5f0265c1db34.png">

But a fill-pattern as in the example below would be more effective.
<img width="953" alt="Screen Shot 2022-10-04 at 21 26 07" src="https://user-images.githubusercontent.com/3343536/193981705-5f005f01-7596-4bd8-8504-56c1eed6638d.png">

Fill-patterns are supported by Mapbox GL and MapLibre. An example can be seen here:
https://observablehq.com/@chrispahm/filling-polygons-with-patterns-in-mapbox-gl-js

And documentation here: 
https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#paint-fill-fill-pattern

Ideally, we can add fill-pattern as an optional configuration component in layers.json. For this particular case, I'd like to use thin black horizontal stripes to differentiate one of the two layers. See PR https://github.com/WFP-VAM/prism-app/pull/576 for a working example of the 'grouped' layers (there are three in this case, but just one of them needs a fill pattern).

**Comment by HarryMytilinaios** [comment]
@wadhwamatic as I am working with this specific task its really hard to me to understand what layers should we enable together and what changes do I have to do in `layers.json` and or `prism.json` in order to replicate what we want exactly here the above PR's are older and I am not really sure how many of the above changes are already merged in master. Also as I did a little bit of digging regarding the fill pattern in the urls above indicates that we will need an svg fill pattern in order to be replaced somewhere. My question is do we need to create this svg on the fly or we can agree on a specific svg pattern and have it locally as a file. Cc @ericboucher

**Comment by wadhwamatic** [comment]
Hi @HarryMytilinaios. You can refer to the latest version of layers.json and prism.json for RBD in master. The layers that we want to overlay are:
- "`ch_idps_phase`" (fill pattern) over  "`ch_phase`" (base layer)
- "`ch_inaccessible_phase`"  (fill pattern) over  "`ch_phase`" (base layer)
- "`ch_urban_phase`"  (fill pattern) over  "`ch_phase`" (base layer)
    
- "`ch_idps_pop3_5`" (fill pattern) over "`ch_pop3_5`"  (base layer)
- "`ch_inaccessible_pop3_5`" (fill pattern) over "`ch_pop3_5`"  (base layer)
- "`ch_urban_pop3_5`" (fill pattern) over "`ch_pop3_5`"  (base layer)

I need to refresh my memory and see if the same location could have IDPs, inaccessible, and urban. If NOT, overlaying all three special populations with a unique pattern for each over the base layer would be worth exploring. Hope this is clear.

Yes, we can use an svg file which is stored locally
