### ISSUE TITLE
Zonal script is blocked

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#580]
Zonal is blocked as a script from an unauthenticated source. This is seen in the current demo version of PRISM Cambodia:
https://prism-khm-internal-demo.surge.sh/

I'm on Chrome Version 105.0.5195.125 (Official Build) (x86_64), Mac OSX

<img width="1440" alt="Screen Shot 2022-10-05 at 17 52 59" src="https://user-images.githubusercontent.com/3343536/194189962-0270ebcc-f352-4d8d-bf79-b3bccb43510b.png">

<img width="1137" alt="Screen Shot 2022-10-05 at 17 53 35" src="https://user-images.githubusercontent.com/3343536/194189981-f152884e-3668-49f7-b338-8d75609950c3.png">

**Comment by DanielJDufour** [comment]
PR is up and ready for review here: https://github.com/WFP-VAM/prism-app/pull/581
