### ISSUE TITLE
Include admin level 2 grouping in 'go to' feature when admin level 3 data is available

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#587]
The 'go to' feature groups the lowest level of admin data with the highest. If we have admin 3 level data available, its grouped by admin 1 which is not ideal for users. We should add admin 2 level groupings in this case. 

The screenshot below is from Cambodia (deployed here: https://prism-khm-internal-demo.surge.sh/)
<img width="1440" alt="Screen Shot 2022-10-11 at 21 12 12" src="https://user-images.githubusercontent.com/3343536/195248570-c9404685-9ca5-4aab-9cf2-35906404517d.png">

**Comment by ericboucher** [comment]
@wadhwamatic do you envision having more than 3 levels in the near future? Or can we assume we can limit to 3 for now?

**Comment by wadhwamatic** [comment]
@ericboucher - we likely will continue to have 3 levels for a while, but I could see 4 as a possibility down the road as we do more regional and global deployments.

**Comment by wadhwamatic** [comment]
@JorgeMartinezG - while you're working on this, please also be aware of https://github.com/WFP-VAM/prism-app/issues/451 and https://github.com/WFP-VAM/prism-app/issues/604 which may be able to be resolved with the solution you proposed
