### ISSUE TITLE
Handle non-responsive GetCapabilities requests 

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#593]
Something can go with the WMS GetCapabilities response. But instead of just failing and allowing the application to load, the loading circle is continuously spinning and the app is unusable. 

We need to better handle this scenario by notifying the user of some unavailable layers but not preventing the app from loading.

<img width="1440" alt="Screen Shot 2022-10-12 at 21 09 53" src="https://user-images.githubusercontent.com/3343536/195497327-1ebc7bed-8773-4e1b-a80e-7afb8319eb89.png">

**Comment by ericboucher** [comment]
@wadhwamatic can you do a few tests a recommend a timeout duration maybe?
