### ISSUE TITLE
Make report text fields configurable

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#629]
I want to be able to configure the text / fields shown in the reports generated in PRISM. Right now, some of the text is hard-coded incorrectly.

Here are 4 specific fields where it's a problem:
1. The report title currently uses the label 'Event name'. This isn't correct and seems to be a copy from ADAM reports
2. Admin labels are hard-coded as 'Province', 'District', 'Township', which are not universal and we may not always have 3 admin levels.
3. 'Sources' text will vary based on the deployment and layers used for the analysis. 
4. Flood maps will change from a simple flooded vs not-flooded layer. We should be able to configure the label in case needed

We need to revisit how these reports are setup so that they can be configured correctly, and so that local variations can be accommodated if needed. 

The incorrect fields that were mentioned are highlighted below:
![PRISM_report_exposure_analysis_08_11_2022](https://user-images.githubusercontent.com/3343536/200743476-f383fafa-6dae-422b-bf20-678d84c8b5a4.png)

**Comment by wadhwamatic** [comment]
@HarryMytilinaios - thanks for the summary and recommendation. Your proposed approach for keys like in the example of APPLICATION_TITLE is clear and makes sense to me. What do you think @ericboucher ?

**Comment by ericboucher** [comment]
Potentially linked to https://github.com/WFP-VAM/prism-app/issues/714

**Comment by wadhwamatic** [comment]
> Yes, I think that makes sense for the title part, but maybe less for the rest of the info. Another option would be to do this at the layer level. So it might be easier to configure. @wadhwamatic maybe you could give us a few examples of different configurations you would like to set up?

@ericboucher - sure I'll add that here soon. I think I'm not fully convinced if we should make this happen within layers or instead follow an approach like what was done with table configuration (in tables.json).

**Comment by HarryMytilinaios** [comment]
How should we approach on this? @wadhwamatic @ericboucher

**Comment by ericboucher** [comment]
@wadhwamatic you mean like what's proposed in https://github.com/WFP-VAM/prism-app/issues/714 ?
I agree that we should probably merge these two tasks.

Amit when you have time, add a bit more info in here/the other issue with a bit more details on your expectations. Then @HarryMytilinaios and I can have a quick meeting to discuss our options. We could indeed introduce a `reports.json` file that leverages the layers defined in `layers.json`. Or add a subsection with details in `layers.json`.

**Comment by wadhwamatic** [comment]
@ericboucher and @HarryMytilinaios - I am open to your suggestions between having a new a `reports.json` file or having this configured within `layers.json`. I know I previously mentioned doing this within `layers.json` but I think we're hitting a saturation point with too many parameters for a layer. We could instead have a layer attribute for a `report_id` which is then configured in `reports.json`. What do you think?

In either case, I would like to be able to configure each of the elements mentioned in this issue: report title, admin level names (ideally this can simply be read from the boundary layer configuration), and footer text.

**Comment by ericboucher** [comment]
Agreed, having a new "reports.json" will likely make things more readable. We will need to do the matching between layers.json and reports.json but that should be fine. For now, we will assume that only one report type per layer_id is possible.

As such this issue is mergeable with https://github.com/WFP-VAM/prism-app/issues/714
