### ISSUE TITLE
Export image no longer works

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#630]
It seems that after reports were were implemented, the ability to export an image no longer works. This is the case whether you run an analysis and enable the export report button or not.

Steps to reproduce:
1. Load any layer in any PRISM deployment
2. Above the legend of the layer, select 'Export' then click on the 'Image' button. Nothing happens

**Comment by catmar22** [comment]
Hello @wadhwamatic I am interested in contributing if at all possible! Could you please provide some more information like some relevant files/locations to specifically look into? Or how export was implemented prior to these changes?

**Comment by wadhwamatic** [comment]
Hi @catmar22 ! Thanks a lot for your interest to contribute. I believe the relevant file is here:
src/components/MapView/Download/index.tsx (and/or elsewhere in that folder). 
And I think the PR which introduced the issue is https://github.com/WFP-VAM/prism-app/pull/556/ 

@ericboucher may be able to give some general guidance

**Comment by wadhwamatic** [comment]
Fixed through https://github.com/WFP-VAM/prism-app/pull/729
