### ISSUE TITLE
[Feature Request]: Replace react-mapbox-gl by react-map-gl

### ISSUE THREAD

**Issue by sifelix** [WFP-VAM/prism-app#675]
### Provide a clear and concise description of what the problem is.

[react-mapbox-gl](https://github.com/alex3165/react-mapbox-gl) is not maintained anymore and is not intuitive to use.

### Provide a clear and concise description of what you want to happen.

[react-map-gl](https://github.com/visgl/react-map-gl) has more stars, is maintained, and seems easier to use (for example for the initial center).

It is compatible with maplibre (cf [here](https://blog.astrid-guenther.de/en/erste-schritte-mit-maplibre/) ).

It could be interesting to replace react-mapbox-gl by react-map-gl to improve the stability and maybe the performance.

**Comment by wadhwamatic** [comment]
@ericboucher - thoughts on this?
