### ISSUE TITLE
Additional UX refinement

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#716]
This set of issues should be addressed as soon as possible but are not blockers for merging PR https://github.com/WFP-VAM/prism-app/pull/688

In order of priority:
- [x] 1. Fix map positioning so that we have consistent placement of the map based on viewing area
- [x] 2. Concatenate admin names in the exposure analysis result table (like other analysis results)
- [x] 3. Make table headers in the exposure analysis result sortable (like other analysis results)
- [x] 4. Allow for a chart view based on national data (i.e. no admin 1 or 2 selected)
- [x] 5. Create a 'table' tab. See Mongolia for example of tables in PRISM
- [x] 6. See issue 808   
- [x] 7. Add an indication of which layers are active in the layer tab
- [x] 8. If you toggle a layer on, reduce opacity, turn it off, then back on - the layer will return to the default opacity but the UI will show the reduced capacity that was set earlier (see screenshot)
- [x] 9. A horizontal scrollbar appears in the layer navigation when some layers are activated (visible on screenshot below) (I think this happens when clicking on the opacity icon for some layers)
- [x] 10. See issue 807
- [x] 11. Make it clearer when more than 4 datasets are available in the chart selection.

<img width="1543" alt="Screenshot 2023-03-20 at 09 15 25" src="https://user-images.githubusercontent.com/3343536/226405367-f782d697-c8aa-4a37-841f-167b4949b1be.png">

<img width="471" alt="Screenshot 2023-04-03 at 10 53 50 AM" src="https://user-images.githubusercontent.com/16843267/229461055-e5dcb7d5-f131-4dc3-8b33-6373b4adbbbc.png">

**Comment by wadhwamatic** [comment]
> 1.  Fix map positioning so that we have consistent placement of the map based on viewing area

Clarifying this point: Right now, all of the initial positioning for the map is based on the previous design without a left panel. When the left panel is open, we're covering a big part of the country. Ideally, we can dynamically reposition the map based on whether or not the left panel is open. This only matters on first load. After that, we can keep the map position consistent whether or not the left panel is open.

Here's an example from Indonesia:
<img width="1497" alt="Screenshot 2023-03-08 at 09 21 51" src="https://user-images.githubusercontent.com/3343536/223784833-61ace4f0-74c2-4c66-8bb6-3473eebc9e7d.png">

vs the original layout:
<img width="1501" alt="Screenshot 2023-03-08 at 09 25 35" src="https://user-images.githubusercontent.com/3343536/223785551-5f5bcd26-37c2-4a5c-af5d-a692ba49760b.png">

**Comment by wadhwamatic** [comment]
>  4. Allow for a chart view based on national data (i.e. no admin 1 or 2 selected)

The admin0 codes needed for national level data are available here:
https://docs.google.com/spreadsheets/d/1kyPMFZzrFkm_R1vc5PIuK-ckjBMEhPGIQoTknbSVHtM/edit?usp=sharing

A few for reference for PRISM:
1. Cambodia = 44
2. Mozambique = 170
3. Zimbabwe = 271

@ericboucher

**Comment by ericboucher** [comment]
@HarryMytilinaios for the map positioning, another option would be to:
 - change the map container size when there is the large drawer and use updateSize without "moving" the map when the drawer is toggle on/off. Not sure if this is possible.
 - if we can do the above, we use a simple function to zoom to the country bounds instead of defining a zoomLevel, lat/long combination.

**Comment by wadhwamatic** [comment]
Created two new issues so that this PR can be merged once the table feature has been implemented:
https://github.com/WFP-VAM/prism-app/issues/808
https://github.com/WFP-VAM/prism-app/issues/807
