### ISSUE TITLE
[Bug]: transparency feature in new UI doesn't work on layers in a group

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#743]
### What happened?

When layers are part of a group, only the first layer's opacity control works in the new UI

### Which country / deployment are you running?

PR https://github.com/WFP-VAM/prism-app/pull/688, country=cambodia

### Add a screenshot (if relevant)

Opacity works for 10-day rainfall aggregate, but not for 1-month rainfall aggregate

<img width="1496" alt="Screenshot 2023-03-07 at 13 17 00" src="https://user-images.githubusercontent.com/3343536/223555263-e322a4e3-607d-4993-a647-dca0b0d39500.png">

<img width="1496" alt="Screenshot 2023-03-07 at 13 16 35" src="https://user-images.githubusercontent.com/3343536/223555287-d7d589b2-2899-42a3-a7c2-424a27c6f142.png">

**Comment by wadhwamatic** [comment]
I just noticed the layer opacity also doesn't work on 'point' type data. See EWS-1294 and Kobo form examples from Cambodia:
<img width="1464" alt="Screenshot 2023-03-07 at 15 00 46" src="https://user-images.githubusercontent.com/3343536/223573833-fbf7d140-aadc-473d-b5e9-86241b62c6d1.png">

<img width="1461" alt="Screenshot 2023-03-07 at 15 01 16" src="https://user-images.githubusercontent.com/3343536/223573863-5f71c062-1266-4ab3-9efb-f3087aa25314.png">

**Comment by ericboucher** [comment]
Fixed for point_data in #752
