### ISSUE TITLE
[Feature Request]: Add start / end dates to admin level data layers

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#751]
### Provide a clear and concise description of what the problem is.

We can add validity days to a data layer, which works well when data rounds are fixed by number of days. But in some cases, the data rounds do not follow this pattern.

### Provide a clear and concise description of what you want to happen.

Allow layer configuration to have a start date and end date attribute. It should read the value from the data file directly. For example, layers.json, I want to be able to add something like:
> "data_field": "ch_phase_class",
> "start_date_field": "start_date",
> "end_date_field": "end_date"

With this approach, each dataset would need to have start and end dates in every round of data.

Or we could do something similar to the approach used with multiple dates:
> "path": "data/rbd/ch_round_{x}.json",  
> "period_dates": {
>     ["1", "2022-01-01", "2022-02-28"],
>     ["2", "2022-03-01", "2022-05-31"],
>     ["3", "2022-05-31", "2022-08-31"],
>     ["4", "2022-09-01", "2022-08-31]"
> ]

In this case, the dataset wouldn't need dates but we'd need to update layers.json each time new data is added.

### Is there anything else you can add about the proposal? You might want to link to related issues here, if you haven't already.

In terms of functionality, this should work the same way as validity periods. In the timeline, any date between the start and end date should show valid data for that layer.

**Comment by wadhwamatic** [comment]
@ericboucher - the datasets used in the RBD CH files have start and end date. For example, see https://github.com/WFP-VAM/prism-app/blob/master/frontend/public/data/rbd/ch/admin1_2023_06_01.json. The fields 'start_date' and 'end_date' are available.

If we can add start/end date as configuration options in layers.json, this would be a good approach from my perspective

**Comment by JulienPathtech** [comment]
@wadhwamatic I have some questions to check that I'm going in the right direction :
- Does it means that indicating a start and end date in a layer imply that there are datas available on every days in between ? 
- What happens if `dates` or `validity` properties are specified ? What properties should I use first ? (Or maybe we should not handle that case)

**Comment by JulienPathtech** [comment]
You can ignore my previous comment. I had a clarification call with eric.
