### ISSUE TITLE
[Feature Request]: Print feature enhancements

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#780]
### Provide a clear and concise description of what the problem is.

Currently the 'print' function its just exporting visible layers without giving any context. Users have requested that we provide a styled map instead.

### Provide a clear and concise description of what you want to happen.

When I click print, I would like to have a preview of a map that includes what is currently in view in PRISM along with a legend, text noting the date, and basic cartographic elements - north star, scale. Ideally each element can be deselected if not needed by the user. 

### Is there anything else you can add about the proposal? You might want to link to related issues here, if you haven't already.

Here's a quick mockup for discussion
![Print](https://user-images.githubusercontent.com/3343536/228702370-1e047728-e7fe-4741-9fc7-4229b9734f26.png)

**Comment by hav142** [comment]
I attempted to retrieve the displayed legend from the webpage and draw it into the current canvas using html2canvas. I will continue working on refining the implementation and adding more details.

![image](https://github.com/WFP-VAM/prism-app/assets/25983260/e568987b-1d07-473f-93e2-9b1be285ecec)

**Comment by wadhwamatic** [comment]
@hav142 - do you have a PR for this issue? We might have someone pick this up but I don't think your changes are in a branch / PR
