### ISSUE TITLE
[Feature Request]: Visualize start and end dates for layers with validity ranges

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#787]
### Provide a clear and concise description of what the problem is.

If a layer has a range of valid dates, the timeline UI shows a continuous line between the start and end dates. When there are consecutive date ranges available, it's impossible to know when a new data point exists.

### Provide a clear and concise description of what you want to happen.

Add markers to the timeline to show when a validity period starts and ends for any layer with date ranges. Since validity ranges can go 'forward' or 'backward', it would be useful to also show direction in the UI. 

In addition, the date picker (calendar) would ideally also give some indication of new ranges. We could use bold text on start/end dates. 

### Is there anything else you can add about the proposal? You might want to link to related issues here, if you haven't already.

Here's a mockup for discussion. 

<img width="1183" alt="Screenshot 2023-04-06 at 10 53 30" src="https://user-images.githubusercontent.com/3343536/230458322-a6d7f44e-0412-4e11-a230-33f88952c284.png">

**Comment by JulienPathtech** [comment]
Hello @wadhwamatic 
- I don't see any backward going validity dates ATM, is it a real use case ? 
- Would it be better to just pick a date range (i.e "2022-02-01 to 2022-06-01" ) instead of a particular date in the timeline ? (Most of the time it's a 100+ days forward)

**Comment by wadhwamatic** [comment]
@JulienPathtech - Eric covered it well. I'd add that we haven't really implemented the ideal state for validity periods because of the issues he referenced. Once those are resolved, the next order of business is to have a clear indication to users of the range of dates that an indicator references. Let me know if you need more clarifications!

**Comment by JulienPathtech** [comment]
I had a call with eric and I understood better, thanks @wadhwamatic  ! 
Is it ok for you if I just add an arrow on the start **or** end date with the direction of the validity ? (In other words, the arrow would display both direction and start or end date information)

**Comment by wadhwamatic** [comment]
@JulienPathtech - great, glad you were able to connect with eric and discuss. Yes, we can use an arrow on just start or end date. I would propose we use start date and experiment a bit to see how clear it is for a user.

**Comment by ericboucher** [comment]
@JulienPathtech it might be worth looking at https://github.com/WFP-VAM/prism-app/issues/751 at the same time or at least make sure what you're implementing here is compatible.
