### ISSUE TITLE
[Bug]: Date validity with mode 'backward' or 'both' fails 

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#788]
### What happened?

If I configure a layer to use validity with mode equal to 'backward' or 'both', the timeline and the date picker do not show valid date ranges, and do not show data before the first available date.

### Which country / deployment are you running?

RBD, ux-revamp/main branch

### Add a screenshot (if relevant)

Layer with mode = 'forward'
<img width="987" alt="Screenshot 2023-04-06 at 16 45 51" src="https://user-images.githubusercontent.com/3343536/230513950-b26c5cbe-7a38-4e71-84c9-04c58bf57312.png">

The same layer with mode = 'backward'
<img width="987" alt="Screenshot 2023-04-06 at 16 46 22" src="https://user-images.githubusercontent.com/3343536/230514012-e9c7df9e-0dc3-4460-b1b5-1a3b48a4f26d.png">

**Comment by HarryMytilinaios** [comment]
@wadhwamatic. I am going to need a little more info on this. What will be appropriate valid time ranges. Can you give some test cases in order to work with and replicate the issue? What layers should I activate. Is there a specific and particular pattern? cc @ericboucher

**Comment by wadhwamatic** [comment]
@HarryMytilinaios - sorry, I see I didn't give enough details here and also removed the config that was on master. I added a branch with two layers configured to demonstrate the issue here:
https://github.com/WFP-VAM/prism-app/tree/rbd-test-backward-dates

This layer uses the 'backwards' config option: Cadre Harmonisé > Phase Classification > Phase classification
And this layer uses the 'both' config option: Cadre Harmonisé > Population > Population in phase 3 to 5

In both cases, the available dates going backwards do not show up. This is what you see in Phase Classification (only today):
<img width="167" alt="Screenshot 2023-05-23 at 22 03 24" src="https://github.com/WFP-VAM/prism-app/assets/3343536/39b2d316-f0fe-4682-a5b4-c4ae15aac09a">

And here's what you see for Population in phase 3 to 5 (dates ahead, not backwards):
<img width="147" alt="Screenshot 2023-05-23 at 22 04 10" src="https://github.com/WFP-VAM/prism-app/assets/3343536/7a774bc9-71c6-4211-89bc-d428b771fd32">

Hopefully this clarifies a bit
