### ISSUE TITLE
[Feature Request]: Provide design options to access layer functionality while the layer is not visible in the left panel

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#793]
### Provide a clear and concise description of what the problem is.

Transparency, downloading layer data, removing a layer, and running an exposure analysis require the layer navigation to be expanded with the layer of interest in view. This means you can't access any of those features if the navigation is collapsed

### Provide a clear and concise description of what you want to happen.

We need some UX / UI options that allow users to access these functions even if the navigation is collapsed or the left panel is hidden completely. We could consider adding a kebab menu or icons for each layer in the legend section.

**Comment by hav142** [comment]
How about adding the icons for transparency control, data download, and layer removal into the legend section, as shown in below picture? It can provide convenient access to the users. However, we should also consider issue #780 which involves obtaining the HTML element of the legend to be drawn onto the canvas.

![legend_mockup](https://github.com/WFP-VAM/prism-app/assets/25983260/a7f88302-07a0-4f20-8266-2cb62f64513e)

**Comment by wadhwamatic** [comment]
Thanks @hav142 - I like the icon approach. @ericboucher - what do you think?

**Comment by ericboucher** [comment]
yes, that seems fine. If we want to have more space, in case the title is longer for example, we could have the icons as a new row at the bottom of the legend

**Comment by wadhwamatic** [comment]
> yes, that seems fine. If we want to have more space, in case the title is longer for example, we could have the icons as a new row at the bottom of the legend

That's a good suggestion as the title can easily break the formatting. @hav142 - please consider this as you start working on this again
