### ISSUE TITLE
[Bug]: Date warnings appear twice

### ISSUE THREAD

**Issue by ericboucher** [WFP-VAM/prism-app#814]
### What happened?

When switching to a new layer. If there is a date conflict, we show a warning and inform the user of the new selected date. For some reason, this warning appears twice. We should only display the warning once.

<img width="1012" alt="Screenshot 2023-04-28 at 2 33 54 PM" src="https://user-images.githubusercontent.com/16843267/235311723-fd6f8d75-b32c-46c7-9d30-e0f68acc6a82.png">

### Which country / deployment are you running?

All

**Comment by wadhwamatic** [comment]
@ericboucher - yes this is annoying and something that was fixed before but was reintroduced at some stage - I think with the new UX
