### ISSUE TITLE
[Bug]: Analysis results with a vulnerability layer at a different admin than the default doesn't render a result

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#816]
### What happened?

If I run analysis while choosing a vulnerability layer at a different admin level than the default, no results are shown. You can see this in Mozambique with the MPI layer, and in Sri Lanka with any of the food security layers

### Which country / deployment are you running?

Mozambique / Sri Lanka on new UX branch

### Add a screenshot (if relevant)

<img width="1487" alt="Screenshot 2023-05-02 at 18 04 03" src="https://user-images.githubusercontent.com/3343536/235815828-5024d872-0c4b-40c3-bd35-2a96135c4c0e.png">

<img width="1493" alt="Screenshot 2023-05-02 at 18 04 12" src="https://user-images.githubusercontent.com/3343536/235815802-9dd018dd-f17d-42be-89f3-5fb7ff6c7bb0.png">

**Comment by wadhwamatic** [comment]
@ericboucher - I'm not sure when this bug was introduced, but this was working previously

**Comment by ericboucher** [comment]
As far as I could tell this doesn't work on master either. I'm attempting to fix this in #818
