### ISSUE TITLE
Improve app responsiveness

### ISSUE THREAD

**Issue by ericboucher** [WFP-VAM/prism-app#823]
### Provide a clear and concise description of what the problem is.

The app is not responsive enough. Just having a small screen seems to create a lot of issues. This should be improved where possible.

### Provide a clear and concise description of what you want to happen.

Think through and implement easy wins for app responsiveness. Ideally, the app should show well on smaller computer screens and tablets.

**Comment by jbperidypathtech** [comment]
I'm trying to refine the scope. After discussion with Eric I understand target devices are Desktop and Tablet.
Then the main issues I can see is on the left panel. What could be done first is : 
- on the left panel, make contents always visible (set a min-width for example for that)
- on the chart tab, fix or set a min-width for the bottom buttons
- on the analysis tab, make content always visible (for example add a scroll bar when content passing behind the bottom buttons)
@wadhwamatic @ericboucher do you see anything else ?
