### ISSUE TITLE
[Bug]: ACLED or KOBO should not prevent the rest of the app from loading

### ISSUE THREAD

**Issue by ericboucher** [WFP-VAM/prism-app#839]
### What happened?

- 

### Which country / deployment are you running?

-

**Comment by wadhwamatic** [comment]
@ericboucher - is this the same issue, or something else? https://github.com/WFP-VAM/prism-app/issues/593

**Comment by HarryMytilinaios** [comment]
@ericboucher @wadhwamatic those 3 issues are linked and I think they have the same solution. https://github.com/WFP-VAM/prism-app/issues/824 https://github.com/WFP-VAM/prism-app/issues/593. I think we can merge them into one issue.
