### ISSUE TITLE
[Bug]: Admin level layers that don't use default boundaries cause the app to hang

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#857]
### What happened?

If I choose an admin level layer which isn't based on the default admin boundaries, the app hangs

### Which country / deployment are you running?

This can be seen in Mozambique and Sri Lanka on master. Moz, see MPI layer. Sri Lanka, see any of the food insecurity layers

Moz: ?baselineLayerId=mpi
Sri Lanka: ?baselineLayerId=food_expenditure

**Comment by wadhwamatic** [comment]
@ericboucher - sorry, I found another regression on master

**Comment by ericboucher** [comment]
cc @HarryMytilinaios
