### ISSUE TITLE
[Bug]: default layer can't be toggled off

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#858]
### What happened?

The default layer feature that is configured in prism.json stopped working at some stage. If I have configured this option and load the app, the default layer correctly displays. But when I toggle the layer off, it will turn off for a moment and then automatically toggle back on.

### Which country / deployment are you running?

Sri Lanka, PR https://github.com/WFP-VAM/prism-app/pull/831 

### Add a screenshot (if relevant)

https://github.com/WFP-VAM/prism-app/assets/3343536/97e9d709-623e-4d6d-9c35-d74d72090a04

**Comment by ericboucher** [comment]
cc @HarryMytilinaios
