### ISSUE TITLE
[Bug]: App failed to load

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#864]
### What happened?

I tried to load PRISM at a government office today here in Zimbabwe but the app never loaded. I assumed it was failing to load the boundary files but it seems to not have reached that stage.

### Which country / deployment are you running?

Zimbabwe, master. https://prism-zwe-new-ux.surge.sh/

### Add a screenshot (if relevant)

![image](https://github.com/WFP-VAM/prism-app/assets/3343536/8055edea-d9fb-4eee-9f99-c45cb4089350)

**Comment by HarryMytilinaios** [comment]
@wadhwamatic I tried hitting the url you provided and it loads without errors or something everything looks normal. @ericboucher can you check also if you have the time?

**Comment by ericboucher** [comment]
Amit was in Zimbabwe, I'm guessing surge is not great for worldwide availability, which might explain why the app was not loading from there.

**Comment by ericboucher** [comment]
@wadhwamatic could you maybe try this? https://twitter.com/surge_sh/status/986960078078013441?s=20

**Comment by wadhwamatic** [comment]
This was pinpointed as an issue with Surge distributions not loading in Zimbabwe. The same issue was found in Sri Lanka. In both cases, using an AWS Amplify instance worked as expected
