### ISSUE TITLE
[Bug]: Chart data missing for EWS-1294 data in Cambodia

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#879]
### What happened?

When I start PRISM Cambodia from a local build or deployment based on master, I get an error 'failed to load' and see a CORS error in the dev console related to Kobo layers but the related layers seem to load ok.

The EWS-1294 layer loads as expected but if you click on a point, the time-series chart does not appear.

### Which country / deployment are you running?

Fails for Cambodia / master. Temp surge deployment: https://many-thingz.surge.sh/

Works correctly on a previous build/deployment:
https://prism-khm-new-ux.surge.sh/

### Add a screenshot (if relevant)

<img width="1505" alt="Screenshot 2023-06-19 at 09 16 47" src="https://github.com/WFP-VAM/prism-app/assets/3343536/1c63fe5a-837a-41b7-b5bf-53112e52ae88">

<img width="1422" alt="Screenshot 2023-06-19 at 09 22 13" src="https://github.com/WFP-VAM/prism-app/assets/3343536/fcf25bdb-b1b8-4474-8f4d-fe0ec5d4c85f">

What I see on a build from master:
<img width="1512" alt="Screenshot 2023-06-19 at 09 23 20" src="https://github.com/WFP-VAM/prism-app/assets/3343536/cfdea669-f340-4ec2-ba5b-8dad8859462f">

Working correctly on a previous build:
<img width="1512" alt="Screenshot 2023-06-19 at 09 23 47" src="https://github.com/WFP-VAM/prism-app/assets/3343536/b663f61b-e44e-4b38-bd6a-d1622b147003">

**Comment by HarryMytilinaios** [comment]
@wadhwamatic the previous build also fails for me. It seems that the server has a CORS error problem I get a 500 error response from server and specifically in this url `https://prism-api.ovio.org/kobo/dates?formId=amkeQ3jwDf9YpifKBh3sez&datetimeField=Date_Dis&measureField=DisTyp&koboUrl=https://kobo.humanitarianresponse.info/api/v2/assets/&filters=status=Approved`. Cc @ericboucher

**Comment by ericboucher** [comment]
Fixed in https://github.com/WFP-VAM/prism-app/pull/821, deployed to the API

**Comment by ericboucher** [comment]
So this solved the `fetch failed`.
@HarryMytilinaios can you look into the charts issue?
