### ISSUE TITLE
[Bug]: Tick marks are no longer visible in the timeline UI

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#890]
### What happened?

It's impossible to see the ticks for dates in the timeline interface as they are white on white now. Previously, they were white on grey.

### Which country / deployment are you running?

All / master

### Add a screenshot (if relevant)

<img width="1762" alt="Screenshot 2023-06-27 at 10 24 38" src="https://github.com/WFP-VAM/prism-app/assets/3343536/e7448273-d5e2-4f20-9ae7-a45639e2ce57">

**Comment by ericboucher** [comment]
@echaidemenos let's try to add subtle grey ticks and see how it looks.
