### ISSUE TITLE
[Feature Request]: Compare a chart indicator over two time periods

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#930]
### Provide a clear and concise description of what the problem is.

The chart feature currently allows a user to visualize and access time-series hazard data for one location and one period (date range) at a time. Users want to be able to compare hazard trends between two places, and for the same place over two time periods. Currently, this requires multiple steps to download data locally and then create charts in another tool for comparison.

### Provide a clear and concise description of what you want to happen.

The PRISM charts UI needs to be updated so that users can either compare two time periods for the same location, or compare two locations for the same time period.

This will require a few changes:
1. The chart UI needs two new elements to either compare periods or compare locations (not both at the same time)
2. If comparing periods, two date pickers are needed
3. If comparing locations, two location drop downs are needed. The level (national, admin 1, admin 2) should be flexible so users can compare across levels if they choose
4. Only one indicator can be used when comparing periods or comparing locations

### Is there anything else you can add about the proposal? You might want to link to related issues here, if you haven't already.

**Mockups**

Compare periods
![01-compare-periods](https://github.com/WFP-VAM/prism-app/assets/3343536/3c76ae25-bd2e-4074-8671-d2749d39b30c)

Compare locations
![02-compare-locations](https://github.com/WFP-VAM/prism-app/assets/3343536/8d0fc7f1-7c98-49d2-add6-3979c7eaa9c9)

**User stories**
1. As an analyst, I need to compare a hazard layer between two time periods, so that I can understand how severe it is compared to a historical event
2. As an analyst, I need to compare a hazard layer between two locations, so that I can determine where to prioritize any response

**Comment by laurentS** [comment]
What would the "Download CSV" button do when comparing locations/periods? Should 2 buttons be shown? no button at all?

**Comment by wadhwamatic** [comment]
Hi @laurentS. The download CSV button should remain in place. We should make each location/period a separate CSV file. The download could either be a zip with both files, or serve two separate CSV files in a single click.
