### ISSUE TITLE
[Feature Request]: The date range for chart data should be flexible

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#931]
### Provide a clear and concise description of what the problem is.

The chart features let's a user see a time-series trend for a 1-year period. That is fine for default behavior, but users often have a specific start / end dates they want to analyze. Currently, this requires them to make multiple chart requests with different end dates to get to the data they want.

### Provide a clear and concise description of what you want to happen.

The following changes are needed in the charts feature:
1. Include separate date pickers for the start and end date. The default values should be an end date of today, and start date of 1 year ago.
3. Do not allow the end date to come before the start date. Alert users if try to select this
4. Do not limit the length of the date range. It can be of any duration
5. Scale the chart based on the selected range
6. Continue to allow multiple indicators to be selected
7. Continue to allow CSV downloads of the data selected 

### Is there anything else you can add about the proposal? You might want to link to related issues here, if you haven't already.

Nice to have: add a slider in the UI to adjust the date range on the chart axis

**Comment by ericboucher** [comment]
@wadhwamatic would you like to open another issue for the slider if you think it can be useful?
`add a slider in the UI to adjust the date range on the chart axis`
