### ISSUE TITLE
[Feature Request]: Composite layer configuration

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#943]
### Provide a clear and concise description of what the problem is.

A single indicator for complex phenomena like drought gives a partial view of climate risks. Many MET agencies produce drought indices, as do sectoral agencies like the ministry of agriculture or water management authorities. The composite indicator allows for multiple indicators to be combined to better describe multifaceted issues. PRISM needs to support the ability to combine multiple layers weights applied into a single / composite layer.

### Provide a clear and concise description of what you want to happen.

1. Create a new layer type called 'composite'
2. The new layer type will reference other 'input' layers based on their layer id
3. Each input layer will have a weight factor
4. The layer will also require rules for intervals and aggregation

Here's an example configuration:
  "cdi": {
    "title": "Combined Drought Index",
    "type": "composite",
      "input_layers": [
        { "id": "spi_1m", "weight": 0.4, "interval": "1-month" },
        { "id": "lst_anomaly", "weight": 0.3, "interval": "10-days" },
        { "id": "ndvi_anomaly", "weight": 0.3, "interval": "10-days" }
      ],
    "aggregation": "pixel",
    "interval": "1-month",
    "date_type": "continuous",
    "start_date": "2020-01-01",
    "end_date": ""
    }

In this example, each input layer's interval is specified since we don't have this info consistently for every layer. Aggregation refers to the level that each output of the composite will be calculated. Values could be pixel or an admin level (admin1, admin2, etc.). Interval refers to the length of the output (10-day, 1-month, 3-month, etc.). Date type would be either continuous or single. Single would have start and end date with the same value (maybe we don't need date type then?). Continuous would mean that a new version is calculated at every interval between the start and end dates. In this example, a new version would be created every month from 2020-01-01 until today.

### Is there anything else you can add about the proposal? You might want to link to related issues here, if you haven't already.

This is one of a few issues for this feature. I'll add more issues and link them here when ready.

**Comment by ericboucher** [comment]
Highlight - the output to display could be a raster (pixel aggregation) or geojson (admin level aggregation)
