### ISSUE TITLE
[Bug]: RBD boundary names have errors related to accents

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#945]
### What happened?

The admin name selection for RBD has errors. This can be seen in the charts module if you select Central African Republic as the country and then try to select an 'admin 1'

### Which country / deployment are you running?

RBD

### Add a screenshot (if relevant)

<img width="512" alt="Screenshot 2023-10-30 at 11 37 01" src="https://github.com/WFP-VAM/prism-app/assets/3343536/ef86096c-1852-4630-a986-8baf3ad7f50a">
<img width="514" alt="Screenshot 2023-10-30 at 11 37 07" src="https://github.com/WFP-VAM/prism-app/assets/3343536/77e49a68-5c19-4d3a-87c2-7d78991a9d6a">

**Comment by ericboucher** [comment]
As a clarification, the issue is in the admin files that need to be replaced to contain correctly formatted admin names.
