### ISSUE TITLE
[Bug]: Clicking on the PRISM header in the top left breaks date functionality

### ISSUE THREAD

**Issue by wadhwamatic** [WFP-VAM/prism-app#976]
### What happened?

If I load a climate layer (10-day rainfall for example), and then click on the 'PRISM' text on the top left, the layer stays visible but the date is removed from the URL. If I then try to change the date through the calendar date picker, clicking on a tick in the timeline, or clicking on the left / ride side of the timeline, the layer doesn't update with the new date and the timeline also doesn't update.

We should remove the hyperlink in the header. It isn't needed

### Which country / deployment are you running?

RBD on main

### Add a screenshot (if relevant)
<img width="1769" alt="Screenshot 2023-11-16 at 11 17 25" src="https://github.com/WFP-VAM/prism-app/assets/3343536/f2b2a971-bd84-4086-a2ef-7585eb0dddec">

**Comment by ericboucher** [comment]
Fixed in #958
