### ISSUE TITLE
Add commit tag to the frontend and the API

### ISSUE THREAD

**Issue by ericboucher** [WFP-VAM/prism-app#984]
### Provide a clear and concise description of what you want to happen.

Add commit tags to the API and the frontend to easily know what is currently deployed.
For example the API could have an endpoint that would return:
`{commit-hash: hash, commit-message: message}`

And the frontend could have a similar data made accessible, maybe hidden in the "about page" or as a standalone page. Thoughts on this @laurentS @echaidemenos since we did something similar on Ovio?

**Comment by laurentS** [comment]
Good idea, always comes in handy at some point when you need to debug things. Better do it before we need it :)
